added missing "not"
git-svn-id: svn+ssh://svn.mandriva.com/svn/soft/msec/trunk@149982 99302b65-d5f7-0310-b3dd-f8cd6f4e3d94

diff --git a/share/msec b/share/msec
--- a/share/msec
+++ b/share/msec
@@ -67,7 +67,7 @@ else
 fi
 
 if [ ! -x "$MSEC" ]; then
-    echo "$MSEC found or not executable. Aborting" 1>&2
+    echo "$MSEC not found or not executable. Aborting" 1>&2
     exit 1
 fi
 
